#!/bin/bash

if [ "$(xdotool search --classname __scratchy getwindowname)" == "" ]; then
	urxvt -bg rgba:0000/0000/0000/d000 --depth 32 -name __scratchy &
	sleep 0.2
fi
i3-msg '[instance="__scratchy"] scratchpad show'

