#!/bin/bash

export PATH=$PATH:/home/andrew/apps/scripts:/home/andrew/apps/scripts/support
img=$1

if [ "${img}" == "" ]; then
	img="/home/andrew/media/photos/pripyat.jpg"
else
	shift
fi

function cleanup {
	dunstctl set-paused false
	screen-timeout normal
}

trap cleanup EXIT HUP INT TERM

dunstctl set-paused true
screen-timeout lock
res=$(xdpyinfo | grep dimens | awk '{print $2}')
convert $img -gravity center -resize ${res}^ -crop ${res}+0+0 +repage -brightness-contrast -10x0 -blur 16x16 RGB:- \
	| /usr/bin/i3lock -e --raw ${res}:rgb --image /dev/stdin $@
cleanup

