#!/bin/bash

export PATH=$PATH:/usr/bin:/home/andrew/apps/scripts:/home/andrew/apps/scripts/support
img=$1

if [ "$(pgrep i3lock)" != "" ]; then
	echo "Screen is already locked."
	exit 1
fi

if [ "${img}" == "" ]; then
	img="/home/andrew/media/photos/pripyat.jpg"
else
	shift
fi

PAUSED_STATUS="$(dunstctl is-paused)"

function cleanup {
	dunstctl set-paused $PAUSED_STATUS
}

trap cleanup EXIT HUP INT TERM

dunstctl set-paused true
sleep 0.2
dunstctl set-paused true
res=$(xdpyinfo | grep dimens | awk '{print $2}')
convert $img -gravity center -resize ${res}^ -crop ${res}+0+0 +repage -brightness-contrast -5x0 -blur 24x24 RGB:- \
	| /usr/bin/i3lock -e --raw ${res}:rgb --image /dev/stdin $@
cleanup

