#!/bin/bash

# You can call this script like this:
# $./volume.sh up
# $./volume.sh down
# $./volume.sh mute

export PATH=$PATH:~/apps/scripts

function get_volume {
	amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
	amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
	percent=$((100 * `brightnessctl g` / `brightnessctl m`))
	/usr/bin/dunstify \
		-i /usr/share/icons/gnome/scalable/status/display-brightness-symbolic.svg \
		-t 2000 \
		-u low \
		-h string:x-canonical-private-synchronous:brightness \
		-h int:value:${percent} \
		"Brightness: "
}

case $1 in
	up)
		brightnessctl set 10%+
		send_notification
		;;
	down)
		cur=$(brightnessctl g)
		if [ "${cur}" -gt 100 ]; then
			brightnessctl set 10%-
			send_notification
		fi
		;;
esac

