#!/bin/bash

# You can call this script like this:
# $./volume.sh up
# $./volume.sh down
# $./volume.sh mute

export PATH=$PATH:~/apps/scripts

PULSE= "-D pulse"

function get_volume {
	amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
	amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
	volume=`get_volume`
	/usr/bin/dunstify \
		-i audio-volume-high \
		-t 2000 \
		-u low \
		-h string:x-canonical-private-synchronous:volume \
		-h int:value:${volume} \
		"Volume: "
}

case $1 in
	up)
		amixer ${PULSE} set Master unmute 5%+ > /dev/null
		send_notification
		;;
	down)
		amixer ${PULSE} set Master unmute 5%- > /dev/null
		send_notification
		;;
	mute)
		# Toggle mute
		amixer ${PULSE} set Master toggle > /dev/null
		if is_mute ; then
			dunstify -i audio-volume-muted -t 2000 -r 9000 -u low "Mute"
		else
			send_notification
		fi
		;;
esac

# save the volume state
# NOTE: no longer needed, thx pulseaudio
#alsactl --file ~/.config/asound.state store

