theme = "modern"
icons = "awesome5"

#[[block]]
#block = "focused_window"
#max_width = 50
#show_marks = "visible"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]

[[block]]
block = "disk_space"
format = "{alias} {available} {unit}"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}%"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
clickable = false
icons = true

[[block]]
block = "net"
device = "enp0s3"
#format = "{speed_down} {speed_up} {graph_down}"
format = "{speed_down} {speed_up}"
interval = 1
use_bits = false

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "{average}°"
chip = "*-isa-*"
inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "battery"
interval = 10
#format = "{percentage}% {time}"
format = "{percentage}%"

[[block]]
block = "sound"
show_volume_when_muted = true

[[block]]
block = "notify"
format = "{state}"

[[block]]
block = "time"
interval = 10
#format = "%a %b %d %l:%M:%S"
format = "%a %b %d %l:%M %P"
