#!/bin/bash

export PATH=$PATH:~/apps/scripts

if [ "$(xdotool search --classname __scratchy getwindowname)" == "" ]; then
	whammy-terminal -name __scratchy &
	sleep 0.2
fi
i3-msg '[instance="__scratchy"] scratchpad show'

